### ISSUE TITLE
Missing instructions and code (?)

### ISSUE THREAD

**Issue by firatozdemir** [siyuhuang/QuantArt#1]
I experience several issues, but I'll list a few here.
- creating conda environment: pip packages within `environment.yaml` includes `- -e .` but `setup.py` is missing in root dir. 
- Under Testing, text says *Follow Datasets and Pre-trained Models to download more datasets and pretrained models. For instance for photo-to-artwork style transfer model, the folder structure should be*, however, I believe it should be landscape-to-artwork by the looks of the folder structure. Then it also becomes clearer that one needs to download `lhq_1024_jpg` and `wikiart` for testing. 
- inside `logs/landscape2art/configs/test_paired.yaml` for the sample test run, `taming.data.paired_image.PairedImageVal` is pointed, however, this class does not exist. I attempted changing `taming.data.paired_image.PairedImageVal` to `taming.data.paired_image.PairedImageTest`, which then runs, but I get corrupted results, see an example below:
![vis_000001](https://github.com/siyuhuang/QuantArt/assets/6260768/74af7ef1-f658-4048-ba70-4829f0572fdd)

Can you have a look to see if you can run examples on a fresh clone on your side? 
Thanks for the great work and making code publicly available!

**Comment by siyuhuang** [comment]
Hi [firatozdemir](https://github.com/firatozdemir), thank you for your feedback and pointing out some issues of this repo. I  have updated the repo. See below. 

- I have removed `- -e .` in `environment.yaml`

- Yes, it should be _landscape-to-artwork_ in texts of testing example. Revised.

- I have updated `taming/data/paired_image.py`. 

- For the quick start example, I ran`bash test.sh` and got correct images. I am not sure why the corruption happens. Please let me know more details.

![image](https://github.com/siyuhuang/QuantArt/assets/30685235/1a4aa7b8-b272-4673-b753-f3dd3b4bc680)

**Comment by firatozdemir** [comment]
Thanks for quick response!

I have virtually no changes to the repository, so I would like to believe the cause is either with the repo, or the model checkpoints. 
I run the same, but get corrupted images for all 4 samples. 
```python main.py --base logs/landscape2art/configs/test_paired.yaml -n quick_start --train false --gpus 0```
I got the same results for both when using GPU and CPU.

Here are some more details from my debugging session:  
Inside taming.models.vqgan_ref.VQModel_Ref, I have the following behavior:  
`quant_x, _, _ = self.encode(x, quantize=True)` operation calls `VectorQuantizer2.forward`. Within VectorQuantizer2 `min_encoding_indices` is all constant and 504 (other constant for other samples). This made me wonder if ckpt is missing weights for the codebooks, but it seems that is not the case.    

Then I checked previous steps. Surprisingly, `taming.modules.diffusionmodules.model.Encoder` that is used as `VQModel_Ref.encoder` behaves strangely already, so it is natural for quantizer to pick the same codeword.  

The first layer of encoder `self.conv_in` maps the input image to [1,128,256,256] 128 channels. For me, each channel is a constant.   
For example, self.conv_in(x)[0,5] is a constant matrix of 0.1582 everywhere. I have another constant for each other channel. From thereon, rest is also naturally corrupted. 
Within the provided ckpt file, encoder.conv_in.weight exists.
So my only theory is that the uploaded ckpt file is different than the one you have to reproduce the results. Can you give it a try with the [ckpt](https://drive.google.com/drive/folders/10fG4-122WfeJ25OOd-dEFZBiBnKtUllE) file from gdrive? 

I don't know how else I can give more details since I am not seeing an error, but rather corrupted reconstructions already starting at the first encoder step for a given test sample. 

Thanks!

**Comment by siyuhuang** [comment]
Thank you for your patient debugging! 

I downloaded the pretrained checkpoint from Google Drive, and it works well. I also asked one of my friends to check if he could replicate the experiment of `bash test.sh`, and he didn't run into any issues.

According to the information you provided, I guess the issue is on not loading checkpoints correctly. Could you plot the system outputs here? I will take a look. In addition, you could check the checkpoint loading process step-by-step in [this line](https://github.com/siyuhuang/QuantArt/blob/4186da2601be7a0e316ee6b9ff5aec66d0a491cf/taming/models/vqgan_ref.py#L86) to see if there is any issue.

**Comment by firatozdemir** [comment]
Thanks for both downloading and asking a friend to verify. I have checked the point where ckpt is loaded and then read into NN variables, it seems to be all fine (initialized variables are replaced with the values from ckpt), hence my hope that the ckpt on GDrive was a wrong one. 

Here is the system output when I run bash test.sh without the gpu parameter (although same result when using gpu):
```bash
bash test.sh
bash: /data/users/firat/miniconda3/lib/libtinfo.so.6: no version information available (required by bash)
Working with z of shape (1, 256, 16, 16) = 65536 dimensions.
VQLPIPSWithDiscriminator running with hinge loss.
Restored from logs/landscape2art/checkpoints/last.ckpt
GPU available: True, used: False
TPU available: False, using: 0 TPU cores
/data/users/firat/miniconda3/envs/quantart/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py:45: UserWarning: GPU available but not used. Set the --gpus flag when calling the script.
  warnings.warn(*args, **kwargs)
accumulate_grad_batches = 1
Setting learning rate to 4.50e-06 = 1 (accumulate_grad_batches) * 1 (num_gpus) * 1 (batchsize) * 4.50e-06 (base_lr)
/data/users/firat/miniconda3/envs/quantart/lib/python3.8/site-packages/torch/cuda/__init__.py:104: UserWarning:
NVIDIA A100 80GB PCIe with CUDA capability sm_80 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the NVIDIA A100 80GB PCIe GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Testing 0 / 4
Testing 1 / 4
Testing 2 / 4
Testing 3 / 4

```

As I said, everything looks fine to me. 
Far fetched, but I tried cpu at last because environment sets up cuda toolkit 10.2, but my system has a lot more recent version. Unfortunately still the same results. 

I will debug some more the first conv operation (conv_in) within encoder that converts input images to 128 constant valued channels (for me). I will get back to you if any updates.

**Comment by siyuhuang** [comment]
I checked your system output. The only difference with mine is this line `NVIDIA A100 80GB PCIe with CUDA capability sm_80 is not compatible with the current PyTorch installation.` 

I have never tried on A100. I ran this code on V100. A100 has different cuda toolkit and configurations. Would you be available to try different GPU models like V100 or 2080/3080?

Also, could you check the model weights before and after [this line](https://github.com/siyuhuang/QuantArt/blob/4186da2601be7a0e316ee6b9ff5aec66d0a491cf/taming/models/vqgan_ref.py#L86), make sure the weights have been actually loaded?

**Comment by firatozdemir** [comment]
I believe the warning of the A100 is not relevant. I also achieve the same results if I run on cpu. 

I also can verify that weights are being loaded (weights after initialization are replaced with the values from ckpt [at this line](https://github.com/siyuhuang/QuantArt/blob/4186da2601be7a0e316ee6b9ff5aec66d0a491cf/taming/models/vqgan_ref.py#L103)).

I can nevertheless try on a different system. I will let you know afterwards. 

Thanks!

**Comment by firatozdemir** [comment]
@siyuhuang I don't know what has changed, but I tried it on another system with A100 and now it works as intended. Sorry for the troubles! I will close the issue now.

**Comment by CJT666** [comment]
> @siyuhuang I don't know what has changed, but I tried it on another system with A100 and now it works as intended. Sorry for the troubles! I will close the issue now.

Hi, did you find the cause of the problem? I ran it with the same results as you had before

**Comment by firatozdemir** [comment]
Unfortunately I did not. It just worked afterwards on another gpu cluster. 
However, albeit irrelevant, I was not able to achieve satisfactory results when training the method on some other domain datasets.
