### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by xiaofeixia2022** [siyuhuang/QuantArt#3]
Hello, author! This is an excellent work. I attempted to reproduce the code but received an error indicating that the "datasets/painter-by-numbers/train_info.csv" file is missing.

**Comment by siyuhuang** [comment]
Could you check [https://www.kaggle.com/competitions/painter-by-numbers/data](https://www.kaggle.com/competitions/painter-by-numbers/data)?

**Comment by xiaofeixia2022** [comment]
Thank you very much! However, a new issue has arisen. When I tried to use the command for the first stage of training, an error occurred: 'FileNotFoundError: [Errno 2] No such file or directory: 'datasets/painter-by-numbers-train.txt'. I couldn't find this file on the website you mentioned earlier

**Comment by siyuhuang** [comment]
I forgot to upload the files for train/test splits. Please see [Readme training](https://github.com/siyuhuang/QuantArt/tree/main#training) for updated instructions to train Stage-1 model.
