### ISSUE TITLE
The problem about training setting

### ISSUE THREAD

**Issue by starsisflying** [siyuhuang/QuantArt#5]
Hello, author! This is an excellent work. 
Regarding the training section in your documentation, you mentioned, 'Four GPUs are recommended but not necessary.' I would like to inquire whether a single Nvidia RTX 3090 is sufficient for the complete training process?

**Comment by siyuhuang** [comment]
One GPU possibly works, as Stage-1 finetunes the VQGAN encoder and decoder from pretrained weights.

**Comment by starsisflying** [comment]
Thanks for your quick and insightful response.
